/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const NotificationId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const GeoPoint = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const ShopUpdate = IDL.Record({
  'title' : IDL.Text,
  'expiredAt' : IDL.Opt(Time),
  'shopId' : IDL.Text,
  'ownerId' : IDL.Principal,
  'expiryDate' : Time,
  'createdAt' : Time,
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'updateId' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'location' : GeoPoint,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'lastKnownLocation' : IDL.Opt(Location),
  'name' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'role' : UserRole,
  'lastUpdated' : Time,
  'phoneNumber' : IDL.Text,
});
export const Shop = IDL.Record({
  'shopImage' : ExternalBlob,
  'shopId' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'isOpen' : IDL.Bool,
  'address' : IDL.Text,
  'shopName' : IDL.Text,
  'category' : IDL.Text,
  'location' : GeoPoint,
});
export const FeedShopUpdate = IDL.Record({
  'title' : IDL.Text,
  'shopCategory' : IDL.Text,
  'shopId' : IDL.Text,
  'ownerId' : IDL.Principal,
  'expiryDate' : Time,
  'createdAt' : Time,
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'updateId' : IDL.Text,
  'shopName' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'location' : GeoPoint,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'shopId' : IDL.Text,
  'createdAt' : Time,
  'recipient' : IDL.Principal,
  'distance' : IDL.Float64,
  'isActive' : IDL.Bool,
  'shopUpdateId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeNotifications' : IDL.Func([IDL.Vec(NotificationId)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createShopUpdate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), Time],
      [IDL.Text],
      [],
    ),
  'deleteShopUpdate' : IDL.Func([IDL.Text], [], []),
  'favoriteShop' : IDL.Func([IDL.Text], [], []),
  'getAllActiveShopUpdates' : IDL.Func([], [IDL.Vec(ShopUpdate)], ['query']),
  'getAllProfilesByRole' : IDL.Func(
      [UserRole],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getAllShopUpdatesForShop' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShopUpdate)],
      ['query'],
    ),
  'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerFavorites' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getCustomerHomeFeed' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(FeedShopUpdate)],
      ['query'],
    ),
  'getExpiredUpdatesForShop' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShopUpdate)],
      ['query'],
    ),
  'getLastKnownLocation' : IDL.Func([], [IDL.Opt(Location)], ['query']),
  'getOtpChallenge' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getPendingNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getShopById' : IDL.Func([IDL.Text], [IDL.Opt(Shop)], ['query']),
  'getShopOpenStatus' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getShopUpdate' : IDL.Func([IDL.Text], [IDL.Opt(ShopUpdate)], ['query']),
  'getShopsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Shop)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isShopFavoritedByCaller' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerShop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, GeoPoint, ExternalBlob],
      [Shop],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, UserRole],
      [],
      [],
    ),
  'setLastKnownLocation' : IDL.Func([Location], [], []),
  'setShopOpenStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'unfavoriteShop' : IDL.Func([IDL.Text], [], []),
  'updateShop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, GeoPoint, ExternalBlob],
      [Shop],
      [],
    ),
  'updateShopUpdate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), Time],
      [],
      [],
    ),
  'verifyOtpToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const NotificationId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const GeoPoint = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const ShopUpdate = IDL.Record({
    'title' : IDL.Text,
    'expiredAt' : IDL.Opt(Time),
    'shopId' : IDL.Text,
    'ownerId' : IDL.Principal,
    'expiryDate' : Time,
    'createdAt' : Time,
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'updateId' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'location' : GeoPoint,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'lastKnownLocation' : IDL.Opt(Location),
    'name' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'role' : UserRole,
    'lastUpdated' : Time,
    'phoneNumber' : IDL.Text,
  });
  const Shop = IDL.Record({
    'shopImage' : ExternalBlob,
    'shopId' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : Time,
    'lastUpdated' : Time,
    'isOpen' : IDL.Bool,
    'address' : IDL.Text,
    'shopName' : IDL.Text,
    'category' : IDL.Text,
    'location' : GeoPoint,
  });
  const FeedShopUpdate = IDL.Record({
    'title' : IDL.Text,
    'shopCategory' : IDL.Text,
    'shopId' : IDL.Text,
    'ownerId' : IDL.Principal,
    'expiryDate' : Time,
    'createdAt' : Time,
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'updateId' : IDL.Text,
    'shopName' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'location' : GeoPoint,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'shopId' : IDL.Text,
    'createdAt' : Time,
    'recipient' : IDL.Principal,
    'distance' : IDL.Float64,
    'isActive' : IDL.Bool,
    'shopUpdateId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeNotifications' : IDL.Func([IDL.Vec(NotificationId)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createShopUpdate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), Time],
        [IDL.Text],
        [],
      ),
    'deleteShopUpdate' : IDL.Func([IDL.Text], [], []),
    'favoriteShop' : IDL.Func([IDL.Text], [], []),
    'getAllActiveShopUpdates' : IDL.Func([], [IDL.Vec(ShopUpdate)], ['query']),
    'getAllProfilesByRole' : IDL.Func(
        [UserRole],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getAllShopUpdatesForShop' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShopUpdate)],
        ['query'],
      ),
    'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerFavorites' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getCustomerHomeFeed' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(FeedShopUpdate)],
        ['query'],
      ),
    'getExpiredUpdatesForShop' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShopUpdate)],
        ['query'],
      ),
    'getLastKnownLocation' : IDL.Func([], [IDL.Opt(Location)], ['query']),
    'getOtpChallenge' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getPendingNotifications' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getShopById' : IDL.Func([IDL.Text], [IDL.Opt(Shop)], ['query']),
    'getShopOpenStatus' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getShopUpdate' : IDL.Func([IDL.Text], [IDL.Opt(ShopUpdate)], ['query']),
    'getShopsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Shop)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isShopFavoritedByCaller' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerShop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, GeoPoint, ExternalBlob],
        [Shop],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, UserRole],
        [],
        [],
      ),
    'setLastKnownLocation' : IDL.Func([Location], [], []),
    'setShopOpenStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'unfavoriteShop' : IDL.Func([IDL.Text], [], []),
    'updateShop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, GeoPoint, ExternalBlob],
        [Shop],
        [],
      ),
    'updateShopUpdate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), Time],
        [],
        [],
      ),
    'verifyOtpToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };