/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const ShopUpdate = IDL.Record({
  'title' : IDL.Text,
  'shopId' : IDL.Principal,
  'expiryDate' : Time,
  'shopLocation' : Location,
  'description' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'lastKnownLocation' : IDL.Opt(Location),
  'createdAt' : Time,
  'role' : UserRole,
  'lastUpdated' : Time,
  'phoneNumber' : IDL.Text,
});
export const Shop = IDL.Record({
  'latitude' : IDL.Float64,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createShopUpdate' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), Time],
      [IDL.Text],
      [],
    ),
  'deleteShopUpdate' : IDL.Func([IDL.Text], [], []),
  'getAllActiveShopUpdates' : IDL.Func([], [IDL.Vec(ShopUpdate)], ['query']),
  'getAllProfilesByRole' : IDL.Func(
      [UserRole],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getAllShopUpdatesForShop' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ShopUpdate)],
      ['query'],
    ),
  'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLastKnownLocation' : IDL.Func([], [IDL.Opt(Location)], ['query']),
  'getOtpChallenge' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getShop' : IDL.Func([IDL.Principal], [IDL.Opt(Shop)], ['query']),
  'getShopUpdate' : IDL.Func([IDL.Text], [IDL.Opt(ShopUpdate)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerShop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, ExternalBlob],
      [Shop],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, UserRole], [], []),
  'setLastKnownLocation' : IDL.Func([Location], [], []),
  'updateShop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, ExternalBlob],
      [Shop],
      [],
    ),
  'updateShopUpdate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), Time],
      [],
      [],
    ),
  'verifyOtpToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const ShopUpdate = IDL.Record({
    'title' : IDL.Text,
    'shopId' : IDL.Principal,
    'expiryDate' : Time,
    'shopLocation' : Location,
    'description' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'lastKnownLocation' : IDL.Opt(Location),
    'createdAt' : Time,
    'role' : UserRole,
    'lastUpdated' : Time,
    'phoneNumber' : IDL.Text,
  });
  const Shop = IDL.Record({
    'latitude' : IDL.Float64,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'lastUpdated' : Time,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createShopUpdate' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          Time,
        ],
        [IDL.Text],
        [],
      ),
    'deleteShopUpdate' : IDL.Func([IDL.Text], [], []),
    'getAllActiveShopUpdates' : IDL.Func([], [IDL.Vec(ShopUpdate)], ['query']),
    'getAllProfilesByRole' : IDL.Func(
        [UserRole],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getAllShopUpdatesForShop' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ShopUpdate)],
        ['query'],
      ),
    'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLastKnownLocation' : IDL.Func([], [IDL.Opt(Location)], ['query']),
    'getOtpChallenge' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getShop' : IDL.Func([IDL.Principal], [IDL.Opt(Shop)], ['query']),
    'getShopUpdate' : IDL.Func([IDL.Text], [IDL.Opt(ShopUpdate)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerShop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, ExternalBlob],
        [Shop],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, UserRole], [], []),
    'setLastKnownLocation' : IDL.Func([Location], [], []),
    'updateShop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, ExternalBlob],
        [Shop],
        [],
      ),
    'updateShopUpdate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), Time],
        [],
        [],
      ),
    'verifyOtpToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };