/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : Time,
}
export interface Shop {
  'latitude' : number,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'longitude' : number,
  'address' : string,
  'category' : string,
  'image' : ExternalBlob,
}
export interface ShopUpdate {
  'title' : string,
  'shopId' : Principal,
  'expiryDate' : Time,
  'shopLocation' : Location,
  'description' : [] | [string],
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserProfile {
  'lastKnownLocation' : [] | [Location],
  'createdAt' : Time,
  'role' : UserRole,
  'lastUpdated' : Time,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createShopUpdate' : ActorMethod<
    [Principal, string, [] | [string], [] | [ExternalBlob], Time],
    string
  >,
  'deleteShopUpdate' : ActorMethod<[string], undefined>,
  'getAllActiveShopUpdates' : ActorMethod<[], Array<ShopUpdate>>,
  'getAllProfilesByRole' : ActorMethod<[UserRole], Array<UserProfile>>,
  'getAllShopUpdatesForShop' : ActorMethod<[Principal], Array<ShopUpdate>>,
  'getAllShops' : ActorMethod<[], Array<Shop>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLastKnownLocation' : ActorMethod<[], [] | [Location]>,
  'getOtpChallenge' : ActorMethod<[string], string>,
  'getShop' : ActorMethod<[Principal], [] | [Shop]>,
  'getShopUpdate' : ActorMethod<[string], [] | [ShopUpdate]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerShop' : ActorMethod<
    [string, string, string, number, number, ExternalBlob],
    Shop
  >,
  'saveCallerUserProfile' : ActorMethod<[string, UserRole], undefined>,
  'setLastKnownLocation' : ActorMethod<[Location], undefined>,
  'updateShop' : ActorMethod<
    [string, string, string, number, number, ExternalBlob],
    Shop
  >,
  'updateShopUpdate' : ActorMethod<
    [string, string, [] | [string], [] | [ExternalBlob], Time],
    undefined
  >,
  'verifyOtpToken' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];